spring:
  application:
    name: demo-app

  datasource:
    url: jdbc:mysql://localhost/testDB
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  
  jpa:
    hibernate:
      ddl-auto: update
